---
- name: Add HashiCorp GPG key (Debian)
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repo (Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install Vagrant (Debian)
  apt:
    name: vagrant
    state: present
    update_cache: yes
