---
- name: Add HashiCorp repo (RedHat)
  yum_repository:
    name: hashicorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: yes

- name: Install Vagrant (RedHat)
  dnf:
    name: vagrant
    state: present
