---
- name: Uninstall apache web server on RHEL
  yum:
    name: httpd
    state: absent
    update_cache: true

# cant work with no systemd in container
#- name: Enable and start the apache2
#  systemd:
#    name: httpd
#    enabled: true
#    state: started