---
- name: Install apache web server on debian/ubuntu
  apt:
    pkg: apache2
    state: present
    update_cache: true
        
- name: Enable and start the apache2
  systemd:
    name: httpd
    enabled: true
    state: started
