---
- name: Install GnuPG
  apt:
    name: gnupg
    state: present

- name: Add CloudStack GPG Key
  apt_key:
    url: http://download.cloudstack.org/release.asc
    state: present

- name: Add CloudStack Repository (Debian)
  apt_repository:
    repo: deb http://download.cloudstack.org/ubuntu jammy 4.22
    state: present
